version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         $(aws ecr get-login --no-include-email --region eu-west-1)
     # build the application image
     - run: docker build -t liran-test/app:$CIRCLE_BRANCH .

     - run: docker tag liran-test:$CIRCLE_BRANCH 549765205618.dkr.ecr.eu-west-1.amazonaws.com/liran-test:$CIRCLE_BRANCH
     # deploy the image
     - run: docker push company/app:$CIRCLE_BRANCH
